- name: Configure NFS shares
  gather_facts: false
  vars_files:
    - vars/sec_vars.yml
    - vars/deployment_vars.yml
    - vars/exports_vars.yml
  hosts: "{{ hosts }}"
  remote_user: "{{ rem_user }}"
  tasks:
    - name: Wait for SSH
      import_tasks:
        file: tests/ssh_response.yml

    - name: Query exisiting exports
      import_tasks:
        file: tests/exports_query.yml

    - name: Iptables present/configured
      import_tasks:
        file: tasks/nfs_ports.yml

    - name: Nfs server present/configured
      import_tasks:
        file: tasks/nfs_exports.yml
