- name: Define NFS exports
  become: true
  lineinfile: 
    path: /etc/exports
    regexp: "{{ ex.path }} {{ ex.node }}" 
    line: "{{ ex.path }} {{ ex.node }}{{ ex.opts }}"
    create: true
    state: present
  ignore_errors: true
  when: ex.path not in expo.stdout_lines
  loop: "{{ exports }}"
  loop_control:
    loop_var: ex

- name: Reload NFS
  become: true
  shell: |
    sudo exportfs -r
